### ISSUE TITLE
ESMPy error with `ESMP_Initialize`

### ISSUE THREAD

**Issue by jkrasting** [esmf-org/esmf#75]
I am using v8.3.1 on Apple M1 and I am encountering an error with `ESMP_Initialize`:

```
regridder = xesmf.Regridder(ds, ds_out, "bilinear")
ESMC_Initialize: Improperly specified optional argument list
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/xesmf/frontend.py", line 773, in __init__
    grid_in, shape_in, input_dims = ds_to_ESMFgrid(
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/xesmf/frontend.py", line 135, in ds_to_ESMFgrid
    grid = Grid.from_xarray(lon.T, lat.T, periodic=periodic, mask=None)
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/xesmf/backend.py", line 111, in from_xarray
    grid = cls(
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/util/decorators.py", line 80, in new_func
    esmp = esmpymanager.Manager(debug = False)
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/api/esmpymanager.py", line 115, in __init__
    ESMP_Initialize(logkind=logkind)
  File "/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/interface/cbindings.py", line 215, in ESMP_Initialize
    raise ValueError('ESMC_Initialize() failed with rc = '+str(rc)+'.    '+
ValueError: ESMC_Initialize() failed with rc = 1000.    Please check the log files (named "*ESMF_LogFile").
```

The release notes for this version give a nod to a similar issue that was fixed in this release.  Any suggestions?

**Comment by rokuingh** [comment]
@jkrasting this seems very much like xesmf is not using an updated version of esmpy. could you attach the file mentioned at the end of the traceback?
`/Users/krasting/miniconda3/envs/py39/lib/python3.9/site-packages/ESMF/interface/cbindings.py`

**Comment by jkrasting** [comment]
Hi @rokuingh - certainly. See attached:  [cbindings.py.txt](https://github.com/esmf-org/esmf/files/9648408/cbindings.py.txt)

**Comment by rokuingh** [comment]
@jkrasting this file differs from v8.3.1 and develop, see [ESMC_Initialize.argtypes](https://github.com/esmf-org/esmf/blob/054f86a8964a67bc95369871b7a287f4801ee154/src/addon/ESMPy/src/ESMF/interface/cbindings.py#L195) for example.

**Comment by jkrasting** [comment]
Thanks @rokuingh.  You're right.  When I installed `xesmf` it overwrote my custom build of esmpy (thought I had turned that off!).  I reinstalled my version of esmpy after install xesmf and everything works OK now.
